stof_doctrine_extensions:
    default_locale: '%kernel.default_locale%'
    translation_fallback: true
    persist_default_translation: true
    orm:
        default:
            translatable: true
            timestampable: false
            blameable: false
            sluggable: false
            tree: false
            loggable: false
            softdeleteable: false
