parameters:

services:
    _defaults:
<<<<<<< Updated upstream
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
=======
        autowire: true
        autoconfigure: true
>>>>>>> Stashed changes

    App\:
        resource: '../src/'
        exclude:
<<<<<<< Updated upstream
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
=======
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\Service\SendGridEmailSender:
        arguments:
            $sendgridApiKey: "%env(string:SENDGRID_API_KEY)%"
            $sendgridFromEmail: "%env(string:SENDGRID_FROM_EMAIL)%"
            $sendgridFromName: "%env(default::SENDGRIDFROM_NAME)%"

    App\Service\ChatbotAnalyseService:
        arguments:
            $questionRepository: '@App\Repository\QuestionRepository'
            $reponseRepository: '@App\Repository\ReponseRepository'
            $httpClient: "@http_client"
            $logger: "@logger"
            $geminiApiKey: "%env(string:GEMINI_API_KEY)%"
>>>>>>> Stashed changes

    App\Service\AiRecommendationService:
        arguments:
            $groqApiKey: "%env(string:GROQ_API_KEY)%"