# config/services.yaml

parameters:
    images_directory: "%kernel.project_dir%/public/uploads/images"
    sendgrid_api_key: '%env(SENDGRID_API_KEY)%'
    sendgrid_from_email: '%env(SENDGRID_FROM_EMAIL)%'
    sendgrid_from_name: '%env(SENDGRID_FROM_NAME)%'
    mobile_text_alerts_api_url: '%env(default::MOBILE_TEXT_ALERTS_API_URL)%'
    mobile_text_alerts_api_key: '%env(default::MOBILE_TEXT_ALERTS_API_KEY)%'
    mobile_text_alerts_sender: '%env(default::MOBILE_TEXT_ALERTS_SENDER)%'
    mobile_text_alerts_template_id: '%env(default::MOBILE_TEXT_ALERTS_TEMPLATE_ID)%'
    sms_default_country_code: '%env(default::SMS_DEFAULT_COUNTRY_CODE)%'
    gemini_api_key: '%env(GEMINI_API_KEY)%'

services:
    _defaults:
        autowire: true      # injecte automatiquement les dépendances
        autoconfigure: true # configure automatiquement les services

    # rend toutes les classes de src/ disponibles comme services
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\Service\SendGridEmailSender:
        arguments:
            $sendgridApiKey: '%sendgrid_api_key%'
            $sendgridFromEmail: '%sendgrid_from_email%'
            $sendgridFromName: '%sendgrid_from_name%'

    App\Service\MobileTextAlertsSmsSender:
        arguments:
            $mobileTextAlertsApiUrl: '%mobile_text_alerts_api_url%'
            $mobileTextAlertsApiKey: '%mobile_text_alerts_api_key%'
            $mobileTextAlertsSender: '%mobile_text_alerts_sender%'
            $smsDefaultCountryCode: '%sms_default_country_code%'
            $mobileTextAlertsTemplateId: '%mobile_text_alerts_template_id%'

    App\Service\ChatbotAnalyseService:
        arguments:
            $questionRepository: '@App\Repository\QuestionRepository'
            $reponseRepository: '@App\Repository\ReponseRepository'
            $httpClient: '@http_client'
            $logger: '@logger'
            $geminiApiKey: '%gemini_api_key%'
